# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jaxonadams
# "service" is the name of this project. This will also be added to your AWS resource names.
service: premium-calculator

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.12
  region: us-west-1

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
    environment:
      JWT_SECRET: ${env:JWT_SECRET}
      DB_HOST: ${env:DB_HOST}
      DB_USER: ${env:DB_USER}
      DB_PASSWORD: ${env:DB_PASSWORD}
      
plugins:
  - serverless-wsgi
  - serverless-python-requirements
